// backend/scripts/updateQuestions.js
const API_URL = 'http://localhost:5000/api';

const updates = [
  // 1. Two Sum
  { title: "Two Sum", description: "Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to target. You may assume that each input would have exactly one solution, and you may not use the same element twice.", examples: [{ input: "nums = [2,7,11,15], target = 9", output: "[0,1]", explanation: "Because nums[0] + nums[1] = 2 + 7 = 9." }, { input: "nums = [3,2,4], target = 6", output: "[1,2]", explanation: "Because nums[1] + nums[2] = 2 + 4 = 6." }], constraints: ["2 <= nums.length <= 10^4", "-10^9 <= nums[i] <= 10^9", "-10^9 <= target <= 10^9", "Only one valid answer exists."], hints: ["Think about how you can efficiently remember values you have already processed.", "Can a hash map help you quickly check whether the required complement exists?", "For each number x, look for target - x in a hash map before inserting x."] },
  // 2. Best Time to Buy and Sell Stock
  { title: "Best Time to Buy and Sell Stock", description: "You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock. Return the maximum profit you can achieve from this transaction. If you cannot achieve any profit, return 0.", examples: [{ input: "prices = [7,1,5,3,6,4]", output: "5", explanation: "Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6-1 = 5." }, { input: "prices = [7,6,4,3,1]", output: "0", explanation: "In this case, no transactions are done and the max profit = 0." }], constraints: ["1 <= prices.length <= 10^5", "0 <= prices[i] <= 10^4"], hints: ["Track the minimum price seen so far.", "Calculate the profit for the current price minus the minimum, and keep the max profit.", "You only need to iterate through the array once."] },
  // 3. Move Zeroes
  { title: "Move Zeroes", description: "Given an integer array nums, move all 0's to the end of it while maintaining the relative order of the non-zero elements. Note that you must do this in-place without making a copy of the array.", examples: [{ input: "nums = [0,1,0,3,12]", output: "[1,3,12,0,0]", explanation: "All non-zero elements are moved to the front in their original order, and zeros are moved to the end." }, { input: "nums = [0]", output: "[0]", explanation: "Single element array, no change." }], constraints: ["1 <= nums.length <= 10^4", "-2^31 <= nums[i] <= 2^31 - 1"], hints: ["Use two pointers: one for reading and one for writing.", "Move all non-zero elements to the front using the write pointer.", "After moving all non-zero elements, fill the rest of the array with zeros."] },
  // 4. Contains Duplicate
  { title: "Contains Duplicate", description: "Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.", examples: [{ input: "nums = [1,2,3,1]", output: "true", explanation: "The value 1 appears twice." }, { input: "nums = [1,2,3,4]", output: "false", explanation: "All elements are distinct." }], constraints: ["1 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"], hints: ["Think about using a hash set to track visited elements.", "If an element is already in the set, return true.", "If you traverse the whole array without finding a duplicate, return false."] },
  // 5. Maximum Subarray
  { title: "Maximum Subarray", description: "Given an integer array nums, find the contiguous subarray (containing at least one number) which has the largest sum and return its sum.", examples: [{ input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6", explanation: "The contiguous subarray [4,-1,2,1] has the largest sum = 6." }, { input: "nums = [1]", output: "1", explanation: "Single element array." }], constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4"], hints: ["Use Kadane's algorithm: iterate through the array and keep a running sum.", "If the running sum becomes negative, reset it to 0.", "Always track the maximum sum seen so far."] },
  // 6. Product of Array Except Self
  { title: "Product of Array Except Self", description: "Given an integer array nums, return an array answer such that answer[i] is equal to the product of all the elements of nums except nums[i]. You must write an algorithm that runs in O(n) time and without using the division operation.", examples: [{ input: "nums = [1,2,3,4]", output: "[24,12,8,6]", explanation: "For index 0: 2*3*4=24, index 1: 1*3*4=12, etc." }, { input: "nums = [-1,1,0,-3,3]", output: "[0,0,9,0,0]", explanation: "Any product with a zero becomes zero." }], constraints: ["2 <= nums.length <= 10^5", "-30 <= nums[i] <= 30"], hints: ["Calculate the prefix products (products of all elements before i).", "Calculate the suffix products (products of all elements after i).", "Multiply the prefix and suffix for each index."] },
  // 7. Find Minimum in Rotated Sorted Array
  { title: "Find Minimum in Rotated Sorted Array", description: "Suppose an array of length n sorted in ascending order is rotated between 1 and n times. Given the sorted rotated array nums of unique elements, return the minimum element of this array.", examples: [{ input: "nums = [3,4,5,1,2]", output: "1", explanation: "The minimum element is 1." }, { input: "nums = [4,5,6,7,0,1,2]", output: "0", explanation: "The minimum element is 0." }], constraints: ["n == nums.length", "1 <= n <= 5000", "-5000 <= nums[i] <= 5000"], hints: ["The array is sorted but rotated. Look for the 'pivot' point.", "Use binary search: if the middle element is greater than the rightmost element, the minimum is on the right half.", "If the middle element is less than the rightmost element, the minimum is on the left half (including the middle)."] },
  // 8. 3Sum
  { title: "3Sum", description: "Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0. Notice that the solution set must not contain duplicate triplets.", examples: [{ input: "nums = [-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]", explanation: "These are the only triplets that sum to 0." }, { input: "nums = [0,1,1]", output: "[]", explanation: "No triplet sums to 0." }], constraints: ["3 <= nums.length <= 3000", "-10^5 <= nums[i] <= 10^5"], hints: ["Sort the array first.", "Fix one number and use two pointers for the remaining two numbers.", "Skip duplicates to avoid duplicate triplets."] },
  // 9. Container With Most Water
  { title: "Container With Most Water", description: "You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container that holds the most water.", examples: [{ input: "height = [1,8,6,2,5,4,8,3,7]", output: "49", explanation: "The max area is between height[1] and height[8] = min(8,7) * 7 = 49." }, { input: "height = [1,1]", output: "1", explanation: "Area = min(1,1)*1 = 1." }], constraints: ["n == height.length", "2 <= n <= 10^5", "0 <= height[i] <= 10^4"], hints: ["Use two pointers, one at the start and one at the end.", "Calculate the area and update the max.", "Move the pointer with the smaller height inward to potentially find a larger area."] },
  // 10. Trapping Rain Water
  { title: "Trapping Rain Water", description: "Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.", examples: [{ input: "height = [0,1,0,2,1,0,1,3,2,1,2,1]", output: "6", explanation: "The total trapped water is 6 units." }, { input: "height = [4,2,0,3,2,5]", output: "9", explanation: "The total trapped water is 9 units." }], constraints: ["n == height.length", "1 <= n <= 2 * 10^4", "0 <= height[i] <= 10^5"], hints: ["For each index, the water trapped depends on the min of max heights on left and right.", "Use two pointers or prefix/suffix max arrays.", "Move the pointer with the smaller max height inward."] },
  // 11. Longest Substring Without Repeating Characters
  { title: "Longest Substring Without Repeating Characters", description: "Given a string s, find the length of the longest substring without repeating characters.", examples: [{ input: "s = \"abcabcbb\"", output: "3", explanation: "The answer is \"abc\", with the length of 3." }, { input: "s = \"bbbbb\"", output: "1", explanation: "The answer is \"b\", with the length of 1." }], constraints: ["0 <= s.length <= 5 * 10^4", "s consists of English letters, digits, symbols and spaces."], hints: ["Use a sliding window with two pointers.", "Use a set to store characters in the current window.", "When a repeat occurs, shrink the window from the left."] },
  // 12. Longest Palindromic Substring
  { title: "Longest Palindromic Substring", description: "Given a string s, return the longest palindromic substring in s.", examples: [{ input: "s = \"babad\"", output: "\"bab\"", explanation: "\"aba\" is also a valid answer." }, { input: "s = \"cbbd\"", output: "\"bb\"", explanation: "\"bb\" is the longest palindromic substring." }], constraints: ["1 <= s.length <= 1000", "s consist of only digits and English letters."], hints: ["Expand around the center for every possible center.", "Handle both odd and even length palindromes.", "Track the start and max length of the longest palindrome found."] },
  // 13. Valid Anagram
  { title: "Valid Anagram", description: "Given two strings s and t, return true if t is an anagram of s, and false otherwise. An Anagram is a word or phrase formed by rearranging the letters of a different word or phrase, typically using all the original letters exactly once.", examples: [{ input: "s = \"anagram\", t = \"nagaram\"", output: "true", explanation: "Both strings have the same characters." }, { input: "s = \"rat\", t = \"car\"", output: "false", explanation: "The characters are different." }], constraints: ["1 <= s.length, t.length <= 5 * 10^4", "s and t consist of lowercase English letters."], hints: ["Count the frequency of each character in s.", "Subtract the frequency of each character in t.", "If all frequencies are zero, it's an anagram."] },
  // 14. Group Anagrams
  { title: "Group Anagrams", description: "Given an array of strings strs, group the anagrams together. You can return the answer in any order.", examples: [{ input: "strs = [\"eat\",\"tea\",\"tan\",\"ate\",\"nat\",\"bat\"]", output: "[[\"bat\"],[\"nat\",\"tan\"],[\"ate\",\"eat\",\"tea\"]]", explanation: "Anagrams are grouped together." }, { input: "strs = [\"\"]", output: "[[\"\"]]", explanation: "Single empty string." }], constraints: ["1 <= strs.length <= 10^4", "0 <= strs[i].length <= 100"], hints: ["Sort each string to use as a key.", "Use a hash map to group strings with the same sorted key.", "Return the values of the hash map."] },
  // 15. Valid Parentheses
  { title: "Valid Parentheses", description: "Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid. An input string is valid if: Open brackets must be closed by the same type of brackets. Open brackets must be closed in the correct order.", examples: [{ input: "s = \"()\"", output: "true", explanation: "Simple matching pair." }, { input: "s = \"()[]{}\"", output: "true", explanation: "All brackets matched correctly." }, { input: "s = \"(]\"", output: "false", explanation: "Mismatched closing bracket." }], constraints: ["1 <= s.length <= 10^4", "s consists of parentheses only '()[]{}'."], hints: ["Think about using a stack data structure.", "When you see an opening bracket, push it onto the stack.", "When you see a closing bracket, check if the top of the stack matches it."] },
  // 16. Top K Frequent Elements
  { title: "Top K Frequent Elements", description: "Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.", examples: [{ input: "nums = [1,1,1,2,2,3], k = 2", output: "[1,2]", explanation: "1 appears 3 times, 2 appears 2 times." }, { input: "nums = [1], k = 1", output: "[1]", explanation: "Single element is the most frequent." }], constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4", "k is in the range [1, the number of unique elements]"], hints: ["Count frequencies using a hash map.", "Use a bucket sort or a min-heap of size k.", "Return the k keys with highest frequencies."] },
  // 17. Design Hash Map
  { title: "Design Hash Map", description: "Design a HashMap without using any built-in hash table libraries. Implement the MyHashMap class with put, get, remove methods.", examples: [{ input: "[\"MyHashMap\",\"put\",\"put\",\"get\",\"get\",\"put\",\"get\",\"remove\",\"get\"] [[],[1,1],[2,2],[1],[3],[2,1],[2],[2],[2]]", output: "[null,null,null,1,-1,null,1,null,-1]", explanation: "Standard operations on a hash map." }], constraints: ["0 <= key, value <= 10^6", "At most 10^4 calls will be made to put, get, and remove."], hints: ["Use an array of buckets.", "Use a linked list or an array within each bucket to handle collisions.", "Calculate the hash code to find the correct bucket."] },
  // 18. Insert Delete GetRandom O(1)
  { title: "Insert Delete GetRandom O(1)", description: "Implement the RandomizedSet class: insert(val), remove(val), and getRandom() returns a random element from the current set of elements. Each element must have a 1/(size) probability of being returned.", examples: [{ input: "[\"RandomizedSet\",\"insert\",\"remove\",\"insert\",\"getRandom\",\"remove\",\"insert\",\"getRandom\"] [[],[1],[2],[2],[],[1],[2],[]]", output: "[null,true,false,true,1,true,false,2]", explanation: "Simulates operations on the randomized set." }], constraints: ["-2^31 <= val <= 2^31 - 1", "At most 2 * 10^5 calls will be made to insert, remove, and getRandom."], hints: ["Use a hash map to store the value and its index.", "Use an array to store the values.", "For deletion, swap the element with the last element and pop it."] },
  // 19. Find All Duplicates in an Array
  { title: "Find All Duplicates in an Array", description: "Given an integer array nums of length n where all the integers are in the range [1, n] and each integer appears once or twice, return an array of all the integers that appear twice.", examples: [{ input: "nums = [4,3,2,7,8,2,3,1]", output: "[2,3]", explanation: "2 and 3 appear twice." }, { input: "nums = [1,1,2]", output: "[1]", explanation: "1 appears twice." }], constraints: ["n == nums.length", "1 <= n <= 10^5", "1 <= nums[i] <= n"], hints: ["Use the index as a marker for visited numbers.", "When you visit a number, mark the number at that index as negative.", "If the number is already negative, it means you've seen it before."] },
  // 20. Longest Consecutive Sequence
  { title: "Longest Consecutive Sequence", description: "Given an unsorted array of integers nums, return the length of the longest consecutive elements sequence. You must write an algorithm that runs in O(n) time.", examples: [{ input: "nums = [100,4,200,1,3,2]", output: "4", explanation: "The longest consecutive elements sequence is [1, 2, 3, 4]." }, { input: "nums = [0,3,7,2,5,8,4,6,0,1]", output: "9", explanation: "The longest consecutive sequence is [0, 1, 2, 3, 4, 5, 6, 7, 8]." }], constraints: ["0 <= nums.length <= 10^5", "-10^9 <= nums[i] <= 10^9"], hints: ["Use a hash set to store all numbers.", "For each number, check if it's the start of a sequence.", "Count the sequence length by checking consecutive numbers."] },
  // 21. Reverse Linked List
  { title: "Reverse Linked List", description: "Given the head of a singly linked list, reverse the list, and return the reversed list.", examples: [{ input: "head = [1,2,3,4,5]", output: "[5,4,3,2,1]", explanation: "The list is reversed." }, { input: "head = [1,2]", output: "[2,1]", explanation: "The list is reversed." }], constraints: ["The number of nodes in the list is in the range [0, 5000]", "-5000 <= Node.val <= 5000"], hints: ["Use three pointers: prev, curr, and next.", "In each step, reverse the pointer of curr to point to prev.", "Move all three pointers forward."] },
  // 22. Merge Two Sorted Lists
  { title: "Merge Two Sorted Lists", description: "You are given the heads of two sorted linked lists list1 and list2. Merge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.", examples: [{ input: "list1 = [1,2,4], list2 = [1,3,4]", output: "[1,1,2,3,4,4]", explanation: "Sorted merged list." }, { input: "list1 = [], list2 = []", output: "[]", explanation: "Both lists are empty." }], constraints: ["The number of nodes in both lists is in the range [0, 50]", "-100 <= Node.val <= 100"], hints: ["Use a dummy head to simplify the process.", "Compare the values of the two current nodes.", "Move the pointer of the smaller value forward."] },
  // 23. Linked List Cycle
  { title: "Linked List Cycle", description: "Given head, the head of a linked list, determine if the linked list has a cycle in it. There is a cycle in a linked list if there is some node in the list that can be reached again by continuously following the next pointer.", examples: [{ input: "head = [3,2,0,-4], pos = 1", output: "true", explanation: "There is a cycle in the linked list." }, { input: "head = [1,2], pos = 0", output: "true", explanation: "There is a cycle in the linked list." }], constraints: ["The number of the nodes in the list is in the range [0, 10^4]", "-10^5 <= Node.val <= 10^5"], hints: ["Use Floyd's Tortoise and Hare algorithm.", "Move a slow pointer by 1 and a fast pointer by 2.", "If they meet, there is a cycle."] },
  // 24. Reorder List
  { title: "Reorder List", description: "You are given the head of a singly linked-list. The list can be represented as L0 -> L1 -> ... -> Ln-1 -> Ln. Reorder the list to be L0 -> Ln -> L1 -> Ln-1 -> L2 -> Ln-2 -> ...", examples: [{ input: "head = [1,2,3,4]", output: "[1,4,2,3]", explanation: "Rearranged as L0->L3->L1->L2." }, { input: "head = [1,2,3,4,5]", output: "[1,5,2,4,3]", explanation: "Rearranged as L0->L4->L1->L3->L2." }], constraints: ["The number of nodes in the list is in the range [1, 5 * 10^4]", "1 <= Node.val <= 1000"], hints: ["Find the middle of the linked list.", "Reverse the second half of the list.", "Merge the two halves by alternating nodes."] },
  // 25. Remove Nth Node From End of List
  { title: "Remove Nth Node From End of List", description: "Given the head of a linked list, remove the nth node from the end of the list and return its head.", examples: [{ input: "head = [1,2,3,4,5], n = 2", output: "[1,2,3,5]", explanation: "The 2nd node from the end (4) is removed." }, { input: "head = [1], n = 1", output: "[]", explanation: "The only node is removed." }], constraints: ["The number of nodes in the list is sz", "1 <= sz <= 30", "1 <= n <= sz"], hints: ["Use two pointers: a fast pointer and a slow pointer.", "Move the fast pointer n+1 steps ahead.", "Move both pointers until the fast pointer reaches the end."] },
  // 26. Min Stack
  { title: "Min Stack", description: "Design a stack that supports push, pop, top, and retrieving the minimum element in constant time. Implement the MinStack class with push, pop, top, and getMin methods.", examples: [{ input: "[\"MinStack\",\"push\",\"push\",\"push\",\"getMin\",\"pop\",\"top\",\"getMin\"] [[],[-2],[0],[-3],[],[],[],[]]", output: "[null,null,null,null,-3,null,0,-2]", explanation: "Operations on the min stack." }], constraints: ["-2^31 <= val <= 2^31 - 1", "Methods pop, top and getMin operations will always be called on non-empty stacks."], hints: ["Use a main stack to store elements.", "Use a second stack to store the minimum element.", "When pushing, compare the new value with the current minimum."] },
  // 27. Evaluate Reverse Polish Notation
  { title: "Evaluate Reverse Polish Notation", description: "You are given an array of strings tokens that represents an arithmetic expression in Reverse Polish Notation. Evaluate the expression and return an integer.", examples: [{ input: "tokens = [\"2\",\"1\",\"+\",\"3\",\"*\"]", output: "9", explanation: "((2 + 1) * 3) = 9." }, { input: "tokens = [\"4\",\"13\",\"5\",\"/\",\"+\"]", output: "6", explanation: "(4 + (13 / 5)) = 6." }], constraints: ["1 <= tokens.length <= 10^4", "tokens[i] is either an operator or an integer"], hints: ["Use a stack to store operands.", "When you see an operator, pop two operands.", "Calculate the result and push it back onto the stack."] },
  // 28. Daily Temperatures
  { title: "Daily Temperatures", description: "Given an array of integers temperatures representing the daily temperatures, return an array answer such that answer[i] is the number of days you have to wait after the ith day to get a warmer temperature.", examples: [{ input: "temperatures = [73,74,75,71,69,72,76,73]", output: "[1,1,4,2,1,1,0,0]", explanation: "For 73, the next warmer is 74 on day 1." }, { input: "temperatures = [30,40,50,60]", output: "[1,1,1,0]", explanation: "Each day is warmer than the previous." }], constraints: ["1 <= temperatures.length <= 10^5", "30 <= temperatures[i] <= 100"], hints: ["Use a monotonic decreasing stack.", "Store indices in the stack.", "When a warmer day is found, pop indices and calculate the difference."] },
  // 29. Largest Rectangle in Histogram
  { title: "Largest Rectangle in Histogram", description: "Given an array of integers heights representing the histogram's bar height where the width of each bar is 1, return the area of the largest rectangle in the histogram.", examples: [{ input: "heights = [2,1,5,6,2,3]", output: "10", explanation: "The largest rectangle has area 10." }, { input: "heights = [2,4]", output: "4", explanation: "The largest rectangle has area 4." }], constraints: ["1 <= heights.length <= 10^5", "0 <= heights[i] <= 10^4"], hints: ["Use a monotonic stack to keep heights in increasing order.", "When a smaller height is encountered, compute the area for the popped bars.", "Push sentinel values to handle remaining bars at the end."] },
  // 30. Implement Queue using Stacks
  { title: "Implement Queue using Stacks", description: "Implement a first in first out (FIFO) queue using only two stacks. Implement the MyQueue class with push, pop, peek, and empty methods.", examples: [{ input: "[\"MyQueue\",\"push\",\"push\",\"peek\",\"pop\",\"empty\"] [[],[1],[2],[],[],[]]", output: "[null,null,null,1,1,false]", explanation: "Standard FIFO operations." }], constraints: ["1 <= x <= 9", "At most 100 calls will be made to push, pop, peek, and empty."], hints: ["Use one stack for input and one stack for output.", "When popping, if the output stack is empty, transfer all elements from the input stack.", "The order is reversed twice, restoring FIFO order."] },
  // 31. Design Circular Queue
  { title: "Design Circular Queue", description: "Design your implementation of the circular queue. The circular queue is a linear data structure in which the operations are performed based on FIFO (First In First Out) principle, and the last position is connected back to the first position to make a circle.", examples: [{ input: "[\"MyCircularQueue\",\"enQueue\",\"enQueue\",\"enQueue\",\"enQueue\",\"Rear\",\"isFull\",\"deQueue\",\"enQueue\",\"Rear\"] [[3],[1],[2],[3],[4],[],[],[],[4],[]]", output: "[null,true,true,true,false,3,true,true,true,4]", explanation: "Standard circular queue operations." }], constraints: ["1 <= k <= 1000", "0 <= value <= 1000"], hints: ["Use an array of size k.", "Use two pointers: front and rear.", "Use a variable to track the current size of the queue."] },
  // 32. Sliding Window Maximum
  { title: "Sliding Window Maximum", description: "You are given an array of integers nums, there is a sliding window of size k which is moving from the very left of the array to the very right. You can only see the k numbers in the window. Return the max sliding window.", examples: [{ input: "nums = [1,3,-1,-3,5,3,6,7], k = 3", output: "[3,3,5,5,6,7]", explanation: "Window position: Max values are [3,3,5,5,6,7]." }, { input: "nums = [1], k = 1", output: "[1]", explanation: "Single element." }], constraints: ["1 <= nums.length <= 10^5", "-10^4 <= nums[i] <= 10^4", "1 <= k <= nums.length"], hints: ["Use a monotonic decreasing deque (double-ended queue).", "Store indices in the deque.", "The front of the deque is always the maximum for the current window."] },
  // 33. Binary Search
  { title: "Binary Search", description: "Given an array of integers nums which is sorted in ascending order, and an integer target, write a function to search target in nums. If target exists, then return its index. Otherwise, return -1.", examples: [{ input: "nums = [-1,0,3,5,9,12], target = 9", output: "4", explanation: "9 exists in nums and its index is 4." }, { input: "nums = [-1,0,3,5,9,12], target = 2", output: "-1", explanation: "2 does not exist, return -1." }], constraints: ["1 <= nums.length <= 10^4", "-10^4 < nums[i], target < 10^4", "All integers are unique."], hints: ["Start by looking at the middle element.", "If target is less than middle, search the left half.", "If target is greater than middle, search the right half."] },
  // 34. Search a 2D Matrix
  { title: "Search a 2D Matrix", description: "You are given an m x n integer matrix with the following properties: Each row is sorted in non-decreasing order. The first integer of each row is greater than the last integer of the previous row. Given an integer target, return true if target is in matrix.", examples: [{ input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 3", output: "true", explanation: "3 is in the matrix." }, { input: "matrix = [[1,3,5,7],[10,11,16,20],[23,30,34,60]], target = 13", output: "false", explanation: "13 is not in the matrix." }], constraints: ["m == matrix.length", "n == matrix[0].length", "1 <= m, n <= 100"], hints: ["Treat the 2D matrix as a 1D sorted array.", "Use binary search on the virtual 1D array.", "Convert the middle index back to row and column."] },
  // 35. Koko Eating Bananas
  { title: "Koko Eating Bananas", description: "Koko loves to eat bananas. There are n piles of bananas, the ith pile has piles[i] bananas. The guards have gone and will come back in h hours. Return the minimum integer k such that she can eat all the bananas within h hours.", examples: [{ input: "piles = [3,6,7,11], h = 8", output: "4", explanation: "Koko can eat at 4 bananas per hour." }, { input: "piles = [30,11,23,4,20], h = 5", output: "30", explanation: "Koko must eat 30 bananas per hour." }], constraints: ["1 <= piles.length <= 10^4", "piles.length <= h <= 10^9", "1 <= piles[i] <= 10^9"], hints: ["Binary search on the eating speed k.", "The minimum k is 1, the maximum k is max(piles).", "For each k, calculate the total hours needed."] },
  // 36. Search in Rotated Sorted Array
  { title: "Search in Rotated Sorted Array", description: "There is an integer array nums sorted in ascending order (with distinct values). Prior to being passed to your function, nums is possibly rotated at an unknown pivot index. Given the array nums after the rotation and an integer target, return the index of target if it is in nums, or -1 if it is not.", examples: [{ input: "nums = [4,5,6,7,0,1,2], target = 0", output: "4", explanation: "0 is at index 4." }, { input: "nums = [4,5,6,7,0,1,2], target = 3", output: "-1", explanation: "3 is not in the array." }], constraints: ["1 <= nums.length <= 5000", "-10^4 <= nums[i] <= 10^4"], hints: ["Use binary search, but the array is split into two sorted halves.", "Check which half is sorted by comparing the middle with the leftmost.", "If the target is within the sorted half, search there; otherwise, search the other half."] },
  // 37. Median of Two Sorted Arrays
  { title: "Median of Two Sorted Arrays", description: "Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays. The overall run time complexity should be O(log (m+n)).", examples: [{ input: "nums1 = [1,3], nums2 = [2]", output: "2.0", explanation: "The merged array is [1,2,3], median is 2." }, { input: "nums1 = [1,2], nums2 = [3,4]", output: "2.5", explanation: "The merged array is [1,2,3,4], median is (2+3)/2 = 2.5." }], constraints: ["nums1.length == m", "nums2.length == n", "0 <= m <= 1000", "0 <= n <= 1000"], hints: ["Use binary search on the smaller array.", "Partition both arrays and ensure the left half is smaller than the right half.", "Calculate the median based on the partition boundaries."] },
  // 38. Sort an Array
  { title: "Sort an Array", description: "Given an array of integers nums, sort the array in ascending order and return it. You must solve the problem without using any built-in sort functions.", examples: [{ input: "nums = [5,2,3,1]", output: "[1,2,3,5]", explanation: "Sorted array." }, { input: "nums = [5,1,1,2,0,0]", output: "[0,0,1,1,2,5]", explanation: "Sorted array." }], constraints: ["1 <= nums.length <= 5 * 10^4", "-5 * 10^4 <= nums[i] <= 5 * 10^4"], hints: ["Use merge sort or quick sort.", "Merge sort: divide the array into halves, sort, and merge.", "Quick sort: pick a pivot and partition around it."] },
  // 39. Merge Intervals
  { title: "Merge Intervals", description: "Given an array of intervals where intervals[i] = [starti, endi], merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.", examples: [{ input: "intervals = [[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]", explanation: "Since [1,3] and [2,6] overlap, merge them into [1,6]." }, { input: "intervals = [[1,4],[4,5]]", output: "[[1,5]]", explanation: "Intervals [1,4] and [4,5] are considered overlapping." }], constraints: ["1 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^4"], hints: ["Sort the intervals by the start time.", "Iterate through the intervals and merge overlapping ones.", "Update the end time to the maximum end seen so far."] },
  // 40. Insert Interval
  { title: "Insert Interval", description: "You are given an array of non-overlapping intervals intervals where intervals[i] = [starti, endi]. Insert newInterval into intervals such that intervals is still sorted in ascending order by starti and intervals still does not have any overlapping intervals.", examples: [{ input: "intervals = [[1,3],[6,9]], newInterval = [2,5]", output: "[[1,5],[6,9]]", explanation: "New interval [2,5] overlaps with [1,3]." }, { input: "intervals = [[1,2],[3,5],[6,7],[8,10],[12,16]], newInterval = [4,8]", output: "[[1,2],[3,10],[12,16]]", explanation: "Merges with [3,5], [6,7], and [8,10]." }], constraints: ["0 <= intervals.length <= 10^4", "intervals[i].length == 2", "0 <= starti <= endi <= 10^5"], hints: ["Add all intervals that end before newInterval starts.", "Merge all overlapping intervals with newInterval.", "Add all intervals that start after newInterval ends."] },
  // 41. Climbing Stairs
  { title: "Climbing Stairs", description: "You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?", examples: [{ input: "n = 2", output: "2", explanation: "1 step + 1 step, or 2 steps." }, { input: "n = 3", output: "3", explanation: "1+1+1, 1+2, 2+1." }], constraints: ["1 <= n <= 45"], hints: ["This is a Fibonacci sequence problem.", "The number of ways to reach step n is the sum of ways to reach n-1 and n-2.", "Use dynamic programming or iterative calculation."] },
  // 42. Power of Two
  { title: "Power of Two", description: "Given an integer n, return true if it is a power of two. An integer n is a power of two if there exists an integer x such that n == 2^x.", examples: [{ input: "n = 1", output: "true", explanation: "2^0 = 1." }, { input: "n = 16", output: "true", explanation: "2^4 = 16." }], constraints: ["-2^31 <= n <= 2^31 - 1"], hints: ["A power of two has exactly one bit set in its binary representation.", "Use bitwise operation n & (n - 1) to clear the lowest set bit.", "If n & (n - 1) is 0, it's a power of two."] },
  // 43. Permutations
  { title: "Permutations", description: "Given an array nums of distinct integers, return all the possible permutations. You can return the answer in any order.", examples: [{ input: "nums = [1,2,3]", output: "[[1,2,3],[1,3,2],[2,1,3],[2,3,1],[3,1,2],[3,2,1]]", explanation: "All possible permutations." }, { input: "nums = [0,1]", output: "[[0,1],[1,0]]", explanation: "All possible permutations." }], constraints: ["1 <= nums.length <= 6", "-10 <= nums[i] <= 10"], hints: ["Use backtracking with a 'used' array.", "At each step, choose a number that hasn't been used.", "Recursively generate the rest of the permutation."] },
  // 44. Maximum Depth of Binary Tree
  { title: "Maximum Depth of Binary Tree", description: "Given the root of a binary tree, return its maximum depth. A binary tree's maximum depth is the number of nodes along the longest path from the root node down to the farthest leaf node.", examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "3", explanation: "The tree has depth 3." }, { input: "root = [1,null,2]", output: "2", explanation: "The tree has depth 2." }], constraints: ["The number of nodes in the tree is in the range [0, 10^4]", "-100 <= Node.val <= 100"], hints: ["Use recursion (DFS).", "The depth of a node is 1 + max(depth of left, depth of right).", "Base case: if the node is null, return 0."] },
  // 45. Invert Binary Tree
  { title: "Invert Binary Tree", description: "Given the root of a binary tree, invert the tree, and return its root. Inverting a binary tree means swapping the left and right children of every node.", examples: [{ input: "root = [4,2,7,1,3,6,9]", output: "[4,7,2,9,6,3,1]", explanation: "The tree is inverted." }, { input: "root = [2,1,3]", output: "[2,3,1]", explanation: "The tree is inverted." }], constraints: ["The number of nodes in the tree is in the range [0, 100]", "-100 <= Node.val <= 100"], hints: ["Use recursion (DFS).", "Swap the left and right children of the current node.", "Recursively invert the left and right subtrees."] },
  // 46. Diameter of Binary Tree
  { title: "Diameter of Binary Tree", description: "Given the root of a binary tree, return the length of the diameter of the tree. The diameter of a binary tree is the length of the longest path between any two nodes in a tree. This path may or may not pass through the root.", examples: [{ input: "root = [1,2,3,4,5]", output: "3", explanation: "The longest path is [4,2,1,3] or [5,2,1,3], length is 3." }, { input: "root = [1,2]", output: "1", explanation: "The longest path is [1,2], length is 1." }], constraints: ["The number of nodes in the tree is in the range [1, 10^4]", "-100 <= Node.val <= 100"], hints: ["Use DFS (recursion).", "For each node, calculate the depth of left and right subtrees.", "The diameter through a node is left depth + right depth. Track the max."] },
  // 47. Validate Binary Search Tree
  { title: "Validate Binary Search Tree", description: "Given the root of a binary tree, determine if it is a valid binary search tree (BST). A valid BST is defined as: The left subtree of a node contains only nodes with keys less than the node's key. The right subtree of a node contains only nodes with keys greater than the node's key.", examples: [{ input: "root = [2,1,3]", output: "true", explanation: "Valid BST." }, { input: "root = [5,1,4,null,null,3,6]", output: "false", explanation: "3 is in the right subtree of 5 but is less than 5." }], constraints: ["The number of nodes in the tree is in the range [1, 10^4]", "-2^31 <= Node.val <= 2^31 - 1"], hints: ["Use DFS (in-order traversal).", "Keep track of the valid range (min, max) for each node.", "For the left child, the range is (min, current node). For the right, it's (current node, max)."] },
  // 48. Lowest Common Ancestor of a Binary Search Tree
  { title: "Lowest Common Ancestor of a Binary Search Tree", description: "Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST. The lowest common ancestor is defined between two nodes p and q as the lowest node in T that has both p and q as descendants.", examples: [{ input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 8", output: "6", explanation: "The LCA of 2 and 8 is 6." }, { input: "root = [6,2,8,0,4,7,9,null,null,3,5], p = 2, q = 4", output: "2", explanation: "The LCA of 2 and 4 is 2." }], constraints: ["The number of nodes in the tree is in the range [2, 10^5]", "-10^9 <= Node.val <= 10^9"], hints: ["Use the BST property: left < root < right.", "Start at the root and compare p and q's values with the current node.", "If both are less, go left. If both are greater, go right. If they split, the current node is the LCA."] },
  // 49. Binary Tree Level Order Traversal
  { title: "Binary Tree Level Order Traversal", description: "Given the root of a binary tree, return the level order traversal of its nodes' values. (i.e., from left to right, level by level).", examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]", explanation: "Level by level traversal." }, { input: "root = [1]", output: "[[1]]", explanation: "Single node." }], constraints: ["The number of nodes in the tree is in the range [0, 2000]", "-1000 <= Node.val <= 1000"], hints: ["Use BFS (Breadth-First Search) with a queue.", "Process one level at a time.", "Store the values of the current level in a separate list."] },
  // 50. Serialize and Deserialize Binary Tree
  { title: "Serialize and Deserialize Binary Tree", description: "Serialization is the process of converting a data structure or object into a sequence of bits so that it can be stored in a file or memory buffer. Design an algorithm to serialize and deserialize a binary tree. There is no restriction on how your serialization/deserialization algorithm should work.", examples: [{ input: "root = [1,2,3,null,null,4,5]", output: "[1,2,3,null,null,4,5]", explanation: "Serializing and deserializing yields the same tree." }, { input: "root = []", output: "[]", explanation: "Empty tree." }], constraints: ["The number of nodes in the tree is in the range [0, 10^4]", "-1000 <= Node.val <= 1000"], hints: ["Use pre-order traversal and include null for missing nodes.", "Use a delimiter (like ',' or ' ') to separate values.", "When deserializing, use a queue and recursively build the tree."] }
];

const updateQuestions = async () => {
  try {
    const allQuestionsRes = await fetch(`${API_URL}/questions`);
    const allQuestionsData = await allQuestionsRes.json();
    let updated = 0;
    let skipped = 0;
    
    for (const update of updates) {
      const matchingQuestion = allQuestionsData.questions.find(q => q.title === update.title);
      if (!matchingQuestion) {
        console.log(`❌ Question not found: ${update.title}`);
        skipped++;
        continue;
      }
      const updateRes = await fetch(`${API_URL}/questions/${matchingQuestion._id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(update)
      });
      if (updateRes.ok) {
        console.log(`✅ Updated: ${update.title}`);
        updated++;
      } else {
        console.log(`❌ Failed to update: ${update.title}`);
        skipped++;
      }
    }
    console.log(`Questions updated: ${updated}`);
    console.log(`Questions skipped: ${skipped}`);
    console.log('✅ Update completed successfully');
    process.exit(0);
  } catch (error) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
};
updateQuestions();